---
title: "Academic Projects"
about:
    template: solana
    links:
        - icon: github
          text: Github
          href: https://www.github.com/linda-wakamoto
        - icon: linkedin
          text: LinkedIn
          href: https://www.linkedin.com/in/lindawakamoto
        - icon: file
          text: Resume
          href: https://docs.google.com/document/d/1nL6tFj4LideodgdAIqla3gtP4cOxkGQuoQSvkvoLmXE/edit?usp=sharing

toc: false
--- 

#### Statistical Computing Project:
    
- **Details:** Independent project using Python and C, predicting apartment listing prices from listing details. Project included data cleaning, data preprocessing, exploratory data analysis and data visualization, and predictive modeling. Produced presentation of findings using Canva.
    
- **Methods Used:** Linear Regression, Kernel Regression (with C), Random Forest, XGBoost, Gradient Boost, Generalized Additive Models

- **Tools Used:** Python, C, R, Canva

#### Predictive and Generative AI Project:
    
- **Details:** Used predictive modeling and generated synthetic data to best model Ads click through rate from user behavior data, using Python. Produced presentation of findings using PowerPoint.
    
- **Methods Used:** Logistic Regression, Random Forest, XGBoost, CatBoost, CTGAN

- **Tools Used:** Python, PowerPoint

#### Statistics Capstone Project

- **Details:** Conducted statistical analysis and data modeling on large-scale data of 1,500 Medicare claims, using R and Excel to analyze correlations between social determinants of health and hypertension, leading to actionable insights. Produced well-documented reports, 5 datasets, and 3 data visualizations to highlight actionable insights, and presented findings in a PowerPoint presentation to stakeholders.
    
- **Methods Used:** Logistic Regression

- **Tools used:** R, Excel, PowerPoint


##### For the code samples for these projects and more: [My GitHub](https://www.github.com/linda-wakamoto)